name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake animations
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=#FF7810&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Debug SVG Content
      - name: Debug SVG Content
        run: |
          ls -la dist/
          cat dist/github-snake.svg || echo "File not found: github-snake.svg"
          cat dist/github-snake-dark.svg || echo "File not found: github-snake-dark.svg"
        shell: bash

      # Step 4: Change SVG snake color to orange (#FF7810)
      - name: Update SVG Snake Color
        run: |
          sed -i 's/stroke="#[^"]*"/stroke="#FF7810"/g' dist/github-snake.svg || echo "Failed to update github-snake.svg"
          sed -i 's/stroke="#[^"]*"/stroke="#FF7810"/g' dist/github-snake-dark.svg || echo "Failed to update github-snake-dark.svg"
        shell: bash

      # Step 5: Deploy to Output Branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"
